#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_a --years 1000 --norm-reward --save-agent --state-rep nothmd --autotune False --disagg P    --n-state 59 &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_b --years 1000 --norm-reward --save-agent --state-rep nothmd --autotune False --disagg LL   --n-state 59 &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_c --years 1000 --norm-reward --save-agent --state-rep nothmd --autotune False --disagg ML   --n-state 59 &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_d --years 1000 --norm-reward --save-agent --state-rep nothmd --autotune False --disagg LD   --n-state 59 &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_f --years 1000 --norm-reward --save-agent --state-rep nothmd --autotune False --disagg HLL  --n-state 59 &
#python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_e --years 100 --norm-reward --state-rep nothmd --autotune False --disagg MD   --n-state 59 &
#python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_g --years 100 --norm-reward --state-rep nothmd --autotune False --disagg HML  --n-state 59 &
#python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_h --years 100 --norm-reward --state-rep nothmd --autotune False --disagg HLD  --n-state 59 &
#python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_i --years 100 --norm-reward --state-rep nothmd --autotune False --disagg HMD  --n-state 59 &
#python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_j --years 100 --norm-reward --state-rep nothmd --autotune False --disagg SHLL --n-state 59 &
#python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_k --years 100 --norm-reward --state-rep nothmd --autotune False --disagg SHLD --n-state 59 &
#python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_l --years 100 --norm-reward --state-rep nothmd --autotune False --disagg HKL  --n-state 59 &
#python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VII_m --years 100 --norm-reward --state-rep nothmd --autotune False --disagg SLL --n-state 59 &

#python3 RunSACChargeWorld.py --agent train_6month_sac_gen_j_299 --save-name 6month_sac_disagg_a --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv

#python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_disagg_a --years 2 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --general True --save-agent True
#echo "+++++++++++++++++++++++++++++++++++++++++"
#python3 RunSACChargeWorld.py --agent train_6month_sac_disagg_a_1 --save-name 6month_sac_disagg_reload --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1m_199 --save-name 6month_sac_disagg_1m_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1m_199 --save-name 6month_sac_disagg_1m_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1m_199 --save-name 6month_sac_disagg_1m_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1m_199 --save-name 6month_sac_disagg_1m_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1m_199 --save-name 6month_sac_disagg_1m_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1m_199 --save-name 6month_sac_disagg_1m_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1m_199 --save-name 6month_sac_disagg_1m_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2m_199 --save-name 6month_sac_disagg_2m_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2m_199 --save-name 6month_sac_disagg_2m_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2m_199 --save-name 6month_sac_disagg_2m_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2m_199 --save-name 6month_sac_disagg_2m_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2m_199 --save-name 6month_sac_disagg_2m_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2m_199 --save-name 6month_sac_disagg_2m_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2m_199 --save-name 6month_sac_disagg_2m_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1n_199 --save-name 6month_sac_disagg_1n_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1n_199 --save-name 6month_sac_disagg_1n_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1n_199 --save-name 6month_sac_disagg_1n_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1n_199 --save-name 6month_sac_disagg_1n_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1n_199 --save-name 6month_sac_disagg_1n_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1n_199 --save-name 6month_sac_disagg_1n_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1n_199 --save-name 6month_sac_disagg_1n_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2n_199 --save-name 6month_sac_disagg_2n_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2n_199 --save-name 6month_sac_disagg_2n_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2n_199 --save-name 6month_sac_disagg_2n_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2n_199 --save-name 6month_sac_disagg_2n_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2n_199 --save-name 6month_sac_disagg_2n_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2n_199 --save-name 6month_sac_disagg_2n_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2n_199 --save-name 6month_sac_disagg_2n_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1o_199 --save-name 6month_sac_disagg_1o_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1o_199 --save-name 6month_sac_disagg_1o_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1o_199 --save-name 6month_sac_disagg_1o_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1o_199 --save-name 6month_sac_disagg_1o_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1o_199 --save-name 6month_sac_disagg_1o_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1o_199 --save-name 6month_sac_disagg_1o_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_1o_199 --save-name 6month_sac_disagg_1o_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2o_199 --save-name 6month_sac_disagg_2o_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2o_199 --save-name 6month_sac_disagg_2o_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2o_199 --save-name 6month_sac_disagg_2o_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2o_199 --save-name 6month_sac_disagg_2o_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2o_199 --save-name 6month_sac_disagg_2o_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2o_199 --save-name 6month_sac_disagg_2o_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_2o_199 --save-name 6month_sac_disagg_2o_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_gen_1m --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True & 
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_gen_2m --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_gen_1n --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg LL --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_gen_2n --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg LL --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_gen_1o --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg P --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_gen_2o --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg P --save-agent True &

#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_3m_199 --save-name 6month_sac_disagg_3m_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_3m_199 --save-name 6month_sac_disagg_3m_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_3m_199 --save-name 6month_sac_disagg_3m_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_3m_199 --save-name 6month_sac_disagg_3m_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_3m_199 --save-name 6month_sac_disagg_3m_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_3m_199 --save-name 6month_sac_disagg_3m_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_3m_199 --save-name 6month_sac_disagg_3m_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_4m_199 --save-name 6month_sac_disagg_4m_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_4m_199 --save-name 6month_sac_disagg_4m_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_4m_199 --save-name 6month_sac_disagg_4m_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_4m_199 --save-name 6month_sac_disagg_4m_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_4m_199 --save-name 6month_sac_disagg_4m_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_4m_199 --save-name 6month_sac_disagg_4m_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_4m_199 --save-name 6month_sac_disagg_4m_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_5m_199 --save-name 6month_sac_disagg_5m_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_5m_199 --save-name 6month_sac_disagg_5m_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_5m_199 --save-name 6month_sac_disagg_5m_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_5m_199 --save-name 6month_sac_disagg_5m_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_5m_199 --save-name 6month_sac_disagg_5m_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_5m_199 --save-name 6month_sac_disagg_5m_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
#nohup python3 RunSACChargeWorld.py --agent train_6month_sac_gen_5m_199 --save-name 6month_sac_disagg_5m_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_PF  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_LL  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_ML  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_LD  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_MD  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_HLL --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_P   --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_PF  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_LL  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_ML  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_LD  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_MD  --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_HLL --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_P   --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1b_199 --save-name 6month_sac_disagg_1b_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1b_199 --save-name 6month_sac_disagg_1b_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1b_199 --save-name 6month_sac_disagg_1b_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1b_199 --save-name 6month_sac_disagg_1b_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1b_199 --save-name 6month_sac_disagg_1b_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1b_199 --save-name 6month_sac_disagg_1b_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1b_199 --save-name 6month_sac_disagg_1b_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1c_199 --save-name 6month_sac_disagg_1c_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1c_199 --save-name 6month_sac_disagg_1c_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1c_199 --save-name 6month_sac_disagg_1c_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1c_199 --save-name 6month_sac_disagg_1c_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1c_199 --save-name 6month_sac_disagg_1c_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1c_199 --save-name 6month_sac_disagg_1c_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1c_199 --save-name 6month_sac_disagg_1c_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1d_199 --save-name 6month_sac_disagg_1d_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1d_199 --save-name 6month_sac_disagg_1d_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1d_199 --save-name 6month_sac_disagg_1d_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1d_199 --save-name 6month_sac_disagg_1d_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1d_199 --save-name 6month_sac_disagg_1d_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1d_199 --save-name 6month_sac_disagg_1d_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1d_199 --save-name 6month_sac_disagg_1d_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1e_199 --save-name 6month_sac_disagg_1e_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1e_199 --save-name 6month_sac_disagg_1e_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1e_199 --save-name 6month_sac_disagg_1e_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1e_199 --save-name 6month_sac_disagg_1e_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1e_199 --save-name 6month_sac_disagg_1e_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1e_199 --save-name 6month_sac_disagg_1e_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1e_199 --save-name 6month_sac_disagg_1e_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &


nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2a_199 --save-name 6month_sac_disagg_2a_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2a_199 --save-name 6month_sac_disagg_2a_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2a_199 --save-name 6month_sac_disagg_2a_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2a_199 --save-name 6month_sac_disagg_2a_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2a_199 --save-name 6month_sac_disagg_2a_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2a_199 --save-name 6month_sac_disagg_2a_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2a_199 --save-name 6month_sac_disagg_2a_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2b_199 --save-name 6month_sac_disagg_2b_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2b_199 --save-name 6month_sac_disagg_2b_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2b_199 --save-name 6month_sac_disagg_2b_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2b_199 --save-name 6month_sac_disagg_2b_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2b_199 --save-name 6month_sac_disagg_2b_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2b_199 --save-name 6month_sac_disagg_2b_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2b_199 --save-name 6month_sac_disagg_2b_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2c_199 --save-name 6month_sac_disagg_2c_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2c_199 --save-name 6month_sac_disagg_2c_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2c_199 --save-name 6month_sac_disagg_2c_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2c_199 --save-name 6month_sac_disagg_2c_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2c_199 --save-name 6month_sac_disagg_2c_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2c_199 --save-name 6month_sac_disagg_2c_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2c_199 --save-name 6month_sac_disagg_2c_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2d_199 --save-name 6month_sac_disagg_2d_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2d_199 --save-name 6month_sac_disagg_2d_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2d_199 --save-name 6month_sac_disagg_2d_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2d_199 --save-name 6month_sac_disagg_2d_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2d_199 --save-name 6month_sac_disagg_2d_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2d_199 --save-name 6month_sac_disagg_2d_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2d_199 --save-name 6month_sac_disagg_2d_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2e_199 --save-name 6month_sac_disagg_2e_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2e_199 --save-name 6month_sac_disagg_2e_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2e_199 --save-name 6month_sac_disagg_2e_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2e_199 --save-name 6month_sac_disagg_2e_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2e_199 --save-name 6month_sac_disagg_2e_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2e_199 --save-name 6month_sac_disagg_2e_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_2e_199 --save-name 6month_sac_disagg_2e_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3a_199 --save-name 6month_sac_disagg_3a_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3a_199 --save-name 6month_sac_disagg_3a_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3a_199 --save-name 6month_sac_disagg_3a_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3a_199 --save-name 6month_sac_disagg_3a_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3a_199 --save-name 6month_sac_disagg_3a_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3a_199 --save-name 6month_sac_disagg_3a_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3a_199 --save-name 6month_sac_disagg_3a_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3b_199 --save-name 6month_sac_disagg_3b_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3b_199 --save-name 6month_sac_disagg_3b_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3b_199 --save-name 6month_sac_disagg_3b_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3b_199 --save-name 6month_sac_disagg_3b_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3b_199 --save-name 6month_sac_disagg_3b_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3b_199 --save-name 6month_sac_disagg_3b_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3b_199 --save-name 6month_sac_disagg_3b_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3c_199 --save-name 6month_sac_disagg_3c_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3c_199 --save-name 6month_sac_disagg_3c_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3c_199 --save-name 6month_sac_disagg_3c_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3c_199 --save-name 6month_sac_disagg_3c_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3c_199 --save-name 6month_sac_disagg_3c_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3c_199 --save-name 6month_sac_disagg_3c_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3c_199 --save-name 6month_sac_disagg_3c_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3d_199 --save-name 6month_sac_disagg_3d_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3d_199 --save-name 6month_sac_disagg_3d_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3d_199 --save-name 6month_sac_disagg_3d_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3d_199 --save-name 6month_sac_disagg_3d_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3d_199 --save-name 6month_sac_disagg_3d_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3d_199 --save-name 6month_sac_disagg_3d_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3d_199 --save-name 6month_sac_disagg_3d_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3e_199 --save-name 6month_sac_disagg_3e_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3e_199 --save-name 6month_sac_disagg_3e_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3e_199 --save-name 6month_sac_disagg_3e_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3e_199 --save-name 6month_sac_disagg_3e_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3e_199 --save-name 6month_sac_disagg_3e_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3e_199 --save-name 6month_sac_disagg_3e_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_3e_199 --save-name 6month_sac_disagg_3e_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4a_199 --save-name 6month_sac_disagg_4a_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4a_199 --save-name 6month_sac_disagg_4a_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4a_199 --save-name 6month_sac_disagg_4a_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4a_199 --save-name 6month_sac_disagg_4a_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4a_199 --save-name 6month_sac_disagg_4a_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4a_199 --save-name 6month_sac_disagg_4a_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4a_199 --save-name 6month_sac_disagg_4a_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4b_199 --save-name 6month_sac_disagg_4b_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4b_199 --save-name 6month_sac_disagg_4b_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4b_199 --save-name 6month_sac_disagg_4b_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4b_199 --save-name 6month_sac_disagg_4b_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4b_199 --save-name 6month_sac_disagg_4b_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4b_199 --save-name 6month_sac_disagg_4b_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4b_199 --save-name 6month_sac_disagg_4b_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4c_199 --save-name 6month_sac_disagg_4c_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4c_199 --save-name 6month_sac_disagg_4c_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4c_199 --save-name 6month_sac_disagg_4c_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4c_199 --save-name 6month_sac_disagg_4c_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4c_199 --save-name 6month_sac_disagg_4c_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4c_199 --save-name 6month_sac_disagg_4c_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4c_199 --save-name 6month_sac_disagg_4c_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4d_199 --save-name 6month_sac_disagg_4d_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4d_199 --save-name 6month_sac_disagg_4d_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4d_199 --save-name 6month_sac_disagg_4d_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4d_199 --save-name 6month_sac_disagg_4d_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4d_199 --save-name 6month_sac_disagg_4d_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4d_199 --save-name 6month_sac_disagg_4d_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4d_199 --save-name 6month_sac_disagg_4d_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4e_199 --save-name 6month_sac_disagg_4e_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4e_199 --save-name 6month_sac_disagg_4e_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4e_199 --save-name 6month_sac_disagg_4e_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4e_199 --save-name 6month_sac_disagg_4e_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4e_199 --save-name 6month_sac_disagg_4e_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4e_199 --save-name 6month_sac_disagg_4e_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_4e_199 --save-name 6month_sac_disagg_4e_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5a_199 --save-name 6month_sac_disagg_5a_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5a_199 --save-name 6month_sac_disagg_5a_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5a_199 --save-name 6month_sac_disagg_5a_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5a_199 --save-name 6month_sac_disagg_5a_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5a_199 --save-name 6month_sac_disagg_5a_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5a_199 --save-name 6month_sac_disagg_5a_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5a_199 --save-name 6month_sac_disagg_5a_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5b_199 --save-name 6month_sac_disagg_5b_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5b_199 --save-name 6month_sac_disagg_5b_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5b_199 --save-name 6month_sac_disagg_5b_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5b_199 --save-name 6month_sac_disagg_5b_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5b_199 --save-name 6month_sac_disagg_5b_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5b_199 --save-name 6month_sac_disagg_5b_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5b_199 --save-name 6month_sac_disagg_5b_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5c_199 --save-name 6month_sac_disagg_5c_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5c_199 --save-name 6month_sac_disagg_5c_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5c_199 --save-name 6month_sac_disagg_5c_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5c_199 --save-name 6month_sac_disagg_5c_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5c_199 --save-name 6month_sac_disagg_5c_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5c_199 --save-name 6month_sac_disagg_5c_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5c_199 --save-name 6month_sac_disagg_5c_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5d_199 --save-name 6month_sac_disagg_5d_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5d_199 --save-name 6month_sac_disagg_5d_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5d_199 --save-name 6month_sac_disagg_5d_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5d_199 --save-name 6month_sac_disagg_5d_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5d_199 --save-name 6month_sac_disagg_5d_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5d_199 --save-name 6month_sac_disagg_5d_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5d_199 --save-name 6month_sac_disagg_5d_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5e_199 --save-name 6month_sac_disagg_5e_PF --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5e_199 --save-name 6month_sac_disagg_5e_LL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5e_199 --save-name 6month_sac_disagg_5e_ML --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg ML --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5e_199 --save-name 6month_sac_disagg_5e_LD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5e_199 --save-name 6month_sac_disagg_5e_MD --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg MD --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5e_199 --save-name 6month_sac_disagg_5e_HLL --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg HLL --file-sessions df_elaad_preproc_l6months.csv &
nohup python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_5e_199 --save-name 6month_sac_disagg_5e_P   --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg P --file-sessions df_elaad_preproc_l6months.csv &

#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1a --pred-noise 0.00 --seed 1 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2a --pred-noise 0.00 --seed 2 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3a --pred-noise 0.00 --seed 3 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4a --pred-noise 0.00 --seed 4 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5a --pred-noise 0.00 --seed 5 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1b --pred-noise 0.01 --seed 1 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2b --pred-noise 0.01 --seed 2 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3b --pred-noise 0.01 --seed 3 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4b --pred-noise 0.01 --seed 4 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5b --pred-noise 0.01 --seed 5 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1c --pred-noise 0.02 --seed 1 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2c --pred-noise 0.02 --seed 2 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3c --pred-noise 0.02 --seed 3 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4c --pred-noise 0.02 --seed 4 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5c --pred-noise 0.02 --seed 5 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1d --pred-noise 0.04 --seed 1 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2d --pred-noise 0.04 --seed 2 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3d --pred-noise 0.04 --seed 3 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4d --pred-noise 0.04 --seed 4 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5d --pred-noise 0.04 --seed 5 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1e --pred-noise 0.06 --seed 1 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2e --pred-noise 0.06 --seed 2 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3e --pred-noise 0.06 --seed 3 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4e --pred-noise 0.06 --seed 4 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5e --pred-noise 0.06 --seed 5 --years 200 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF --save-agent True &
