python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_a --years 50 --norm-reward --state-rep nothmd --autotune False --disagg P    --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_b --years 50 --norm-reward --state-rep nothmd --autotune False --disagg LL   --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_c --years 50 --norm-reward --state-rep nothmd --autotune False --disagg ML   --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_d --years 50 --norm-reward --state-rep nothmd --autotune False --disagg LD   --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_e --years 50 --norm-reward --state-rep nothmd --autotune False --disagg MD   --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_f --years 50 --norm-reward --state-rep nothmd --autotune False --disagg HLL  --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_g --years 50 --norm-reward --state-rep nothmd --autotune False --disagg HML  --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_h --years 50 --norm-reward --state-rep nothmd --autotune False --disagg HLD  --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_i --years 50 --norm-reward --state-rep nothmd --autotune False --disagg HMD  --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_j --years 50 --norm-reward --state-rep nothmd --autotune False --disagg SHLL --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_k --years 50 --norm-reward --state-rep nothmd --autotune False --disagg SHLD --n-state 59 &
python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_VI_l --years 50 --norm-reward --state-rep nothmd --autotune False --disagg HKL  --n-state 59 &
