#nohup python3 RunChargeWorld.py --agent NoV2G --save-name apr_NoV2G_pred_noise_a --pred-noise 0.000 --file-sessions df_elaad_preproc_marapr.csv &
#nohup python3 RunChargeWorld.py --agent NoV2G --save-name apr_NoV2G_pred_noise_b --pred-noise 0.001 --file-sessions df_elaad_preproc_marapr.csv &
#nohup python3 RunChargeWorld.py --agent NoV2G --save-name apr_NoV2G_pred_noise_c --pred-noise 0.025 --file-sessions df_elaad_preproc_marapr.csv &
#nohup python3 RunChargeWorld.py --agent NoV2G --save-name apr_NoV2G_pred_noise_d --pred-noise 0.050 --file-sessions df_elaad_preproc_marapr.csv &
#nohup python3 RunChargeWorld.py --agent NoV2G --save-name apr_NoV2G_pred_noise_e --pred-noise 0.100 --file-sessions df_elaad_preproc_marapr.csv &
#nohup python3 RunChargeWorld.py --agent Optim --save-name apr_Optim_pred_noise_a --pred-noise 0.000 --file-sessions df_elaad_preproc_marapr.csv &
#nohup python3 RunChargeWorld.py --agent Optim --save-name apr_Optim_pred_noise_b --pred-noise 0.001 --file-sessions df_elaad_preproc_marapr.csv &
#nohup python3 RunChargeWorld.py --agent Optim --save-name apr_Optim_pred_noise_c --pred-noise 0.025 --file-sessions df_elaad_preproc_marapr.csv &
#nohup python3 RunChargeWorld.py --agent Optim --save-name apr_Optim_pred_noise_d --pred-noise 0.050 --file-sessions df_elaad_preproc_marapr.csv &
#nohup python3 RunChargeWorld.py --agent Optim --save-name apr_Optim_pred_noise_e --pred-noise 0.100 --file-sessions df_elaad_preproc_marapr.csv &

nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1a --pred-noise 0.00 --seed 1 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2a --pred-noise 0.00 --seed 2 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3a --pred-noise 0.00 --seed 3 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4a --pred-noise 0.00 --seed 4 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5a --pred-noise 0.00 --seed 5 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1b --pred-noise 0.01 --seed 1 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2b --pred-noise 0.01 --seed 2 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3b --pred-noise 0.01 --seed 3 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4b --pred-noise 0.01 --seed 4 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5b --pred-noise 0.01 --seed 5 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1c --pred-noise 0.02 --seed 1 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2c --pred-noise 0.02 --seed 2 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3c --pred-noise 0.02 --seed 3 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4c --pred-noise 0.02 --seed 4 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5c --pred-noise 0.02 --seed 5 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1d --pred-noise 0.04 --seed 1 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2d --pred-noise 0.04 --seed 2 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3d --pred-noise 0.04 --seed 3 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4d --pred-noise 0.04 --seed 4 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5d --pred-noise 0.04 --seed 5 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_1e --pred-noise 0.06 --seed 1 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_2e --pred-noise 0.06 --seed 2 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_3e --pred-noise 0.06 --seed 3 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_4e --pred-noise 0.06 --seed 4 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name 6month_sac_pred_noise_5e --pred-noise 0.06 --seed 5 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True --disagg PF &
#nohup python3 RunSACChargeWorld.py --agent SAC-sagg --save-name month_sac_6pred_noise_1a --pred-noise 0.00 --years 300 --batch-size 512 --learning-starts 0 --alpha 0.03 --rng-test True --policy-frequency 4 --target-network-frequency 2 --general True & 
