#{ time python3 time.py 2> /dev/null ; } 2>> time.txt
#
{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_PF  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } > time/time_SACPF.txt 
{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_PF  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_SACPF.txt 
{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_PF  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_SACPF.txt 
{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_PF  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_SACPF.txt 
{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_PF  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg PF  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_SACPF.txt

{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_LL  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } > time/time_SACLL.txt
{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_LL  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_SACLL.txt
{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_LL  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_SACLL.txt
{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_LL  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_SACLL.txt
{ time python3 RunSACChargeWorld.py --agent train_6month_sac_pred_noise_1a_199 --save-name 6month_sac_disagg_1a_LL  --seed 1 --pred-noise 0.00 --years 1 --batch-size 512 --learning-starts 0 --alpha 0.02 --rng-test True --test True --policy-frequency 4 --target-network-frequency 2 --disagg LL  --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_SACLL.txt

{ time python3 RunChargeWorld.py --agent ASAP  --save-name l6_ASAP  --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } > time/time_asap.txt
{ time python3 RunChargeWorld.py --agent ASAP  --save-name l6_ASAP  --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_asap.txt
{ time python3 RunChargeWorld.py --agent ASAP  --save-name l6_ASAP  --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_asap.txt
{ time python3 RunChargeWorld.py --agent ASAP  --save-name l6_ASAP  --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_asap.txt
{ time python3 RunChargeWorld.py --agent ASAP  --save-name l6_ASAP  --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_asap.txt

{ time python3 RunChargeWorld.py --agent NoV2G --save-name l6_NoV2G --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } > time/time_nov2g.txt
{ time python3 RunChargeWorld.py --agent NoV2G --save-name l6_NoV2G --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_nov2g.txt
{ time python3 RunChargeWorld.py --agent NoV2G --save-name l6_NoV2G --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_nov2g.txt
{ time python3 RunChargeWorld.py --agent NoV2G --save-name l6_NoV2G --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_nov2g.txt
{ time python3 RunChargeWorld.py --agent NoV2G --save-name l6_NoV2G --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_nov2g.txt

{ time python3 RunChargeWorld.py --agent Optim --save-name l6_Optim --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } > time/time_optim.txt
{ time python3 RunChargeWorld.py --agent Optim --save-name l6_Optim --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_optim.txt
{ time python3 RunChargeWorld.py --agent Optim --save-name l6_Optim --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_optim.txt
{ time python3 RunChargeWorld.py --agent Optim --save-name l6_Optim --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_optim.txt
{ time python3 RunChargeWorld.py --agent Optim --save-name l6_Optim --summary True --file-sessions df_elaad_preproc_l6months.csv 2> /dev/null ; } >> time/time_optim.txt
